name: BlogCI

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Source file
      uses: actions/checkout@v2
      with:
        ref: source

    - name: Prepare Node env
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    - name: Set Env
      env:
        GPAGES_TOKEN: ${{ secrets.GPAGES_TOKEN }}
      run: |
        git config --global user.name 'Neutralization'
        git config --global user.email 'Neutralization@users.noreply.github.com'
        sed -i "s/GPAGES_TOKEN/$GPAGES_TOKEN/g" ./_config.yml

    - name: Hexo
      run: |
        npm install hexo
        npm install
        npx hexo clean
        npx hexo g -d